[build]
  publish = "web"
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/dashboard.js"
  [headers.values]
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "/dashboard.css"
  [headers.values]
    Cache-Control = "public, max-age=300"
